spring:
  datasource:
      name: test
      url: jdbc:mysql://127.0.0.1/test
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  main:
    web-environment: true

  # redis test 配置
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1


